/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as UseRefRouteImport } from './routes/useRef'
import { Route as UserListRouteImport } from './routes/userList'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const UseRefRoute = UseRefRouteImport.update({
  id: '/useRef',
  path: '/useRef',
  getParentRoute: () => rootRouteImport,
} as any)
const UserListRoute = UserListRouteImport.update({
  id: '/userList',
  path: '/userList',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/useRef': typeof UseRefRoute
  '/userList': typeof UserListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/useRef': typeof UseRefRoute
  '/userList': typeof UserListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/useRef': typeof UseRefRoute
  '/userList': typeof UserListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/useRef' | '/userList'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/useRef' | '/userList'
  id: '__root__' | '/' | '/about' | '/useRef' | '/userList'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  UseRefRoute: typeof UseRefRoute
  UserListRoute: typeof UserListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useRef': {
      id: '/useRef'
      path: '/useRef'
      fullPath: '/useRef'
      preLoaderRoute: typeof UseRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/userList': {
      id: '/userList'
      path: '/userList'
      fullPath: '/userList'
      preLoaderRoute: typeof UserListRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  UseRefRoute: UseRefRoute,
  UserListRoute: UserListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
